CREATE TABLE [dbo].[HechosDynamics365] (
    [Entry No_]                      BIGINT         NULL,
    [G_L Account No_]                BIGINT         NULL,
    [Posting Date]                   DATE           NULL,
    [Document Type]                  BIGINT         NULL,
    [Amount]                         FLOAT (53)     NULL,
    [Global Dimension 1 Code]        NVARCHAR (MAX) NULL,
    [Source Code]                    NVARCHAR (MAX) NULL,
    [System-Created Entry]           BIGINT         NULL,
    [Prior-Year Entry]               BIGINT         NULL,
    [Job No_]                        NVARCHAR (MAX) NULL,
    [Quantity]                       BIGINT         NULL,
    [VAT Amount]                     FLOAT (53)     NULL,
    [Business Unit Code]             NVARCHAR (MAX) NULL,
    [Reason Code]                    NVARCHAR (MAX) NULL,
    [Gen_ Posting Type]              BIGINT         NULL,
    [Gen_ Bus_ Posting Group]        NVARCHAR (MAX) NULL,
    [Bal_ Account Type]              BIGINT         NULL,
    [Transaction No_]                BIGINT         NULL,
    [Debit Amount]                   FLOAT (53)     NULL,
    [Credit Amount]                  FLOAT (53)     NULL,
    [Document Date]                  NVARCHAR (MAX) NULL,
    [Source Type]                    BIGINT         NULL,
    [Tax Area Code]                  NVARCHAR (MAX) NULL,
    [Tax Liable]                     BIGINT         NULL,
    [Tax Group Code]                 NVARCHAR (MAX) NULL,
    [Use Tax]                        BIGINT         NULL,
    [VAT Bus_ Posting Group]         NVARCHAR (MAX) NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (MAX) NULL,
    [Additional-Currency Amount]     BIGINT         NULL,
    [Add_-Currency Debit Amount]     BIGINT         NULL,
    [Add_-Currency Credit Amount]    BIGINT         NULL,
    [Close Income Statement Dim_ ID] BIGINT         NULL,
    [IC Partner Code]                NVARCHAR (MAX) NULL,
    [Reversed]                       BIGINT         NULL,
    [Reversed by Entry No_]          BIGINT         NULL,
    [Reversed Entry No_]             BIGINT         NULL,
    [Dimension Set ID]               BIGINT         NULL,
    [Prod_ Order No_]                NVARCHAR (MAX) NULL,
    [FA Entry Type]                  BIGINT         NULL,
    [FA Entry No_]                   BIGINT         NULL,
    [New G_L Account No_]            NVARCHAR (MAX) NULL,
    [Old G_L Account No_]            NVARCHAR (MAX) NULL,
    [Updated]                        BIGINT         NULL,
    [Period Trans_ No_]              BIGINT         NULL,
    [Cost Entry No_]                 BIGINT         NULL,
    [Description_]                   NVARCHAR (MAX) NULL
);


GO

